// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BtnPreloaderController from "./btn_preloader_controller"
application.register("btn-preloader", BtnPreloaderController)

import CheckboxesController from "./checkboxes_controller"
application.register("checkboxes", CheckboxesController)

import ClearFormController from "./clear_form_controller"
application.register("clear-form", ClearFormController)

import CollapseController from "./collapse_controller"
application.register("collapse", CollapseController)

import ConfirmController from "./confirm_controller"
application.register("confirm", ConfirmController)

import ExpandTextController from "./expand_text_controller"
application.register("expand-text", ExpandTextController)

import FancyboxController from "./fancybox_controller"
application.register("fancybox", FancyboxController)

import LayerController from "./layer_controller"
application.register("layer", LayerController)

import MapController from "./map_controller"
application.register("map", MapController)

import NoImageController from "./no_image_controller"
application.register("no-image", NoImageController)

import NoticesController from "./notices_controller"
application.register("notices", NoticesController)

import PagyInitializerController from "./pagy_initializer_controller"
application.register("pagy-initializer", PagyInitializerController)

import SwiperController from "./swiper_controller"
application.register("swiper", SwiperController)
